---
- name: Gerar chave SSH se não existir
  become: yes
  command: ssh-keygen -t rsa -b 2048 -f /home/{{ target_user }}/.ssh/id_rsa -q -N ""
  args:
    creates: /home/{{ target_user }}/.ssh/id_rsa

- name: Copiar chave pública
  become: yes
  copy:
    content: "{{ ssh_pub_key }}"
    dest: /home/{{ target_user }}/.ssh/authorized_keys

- name: Copiar chave privada
  become: yes
  copy:
    content: "{{ ssh_key }}"
    dest: /home/{{ target_user }}/.ssh/id_rsa
    mode: '0600'

- name: Copiar arquivo de configuração SSH
  become: yes
  copy:
    content: "{{ ssh_config }}"
    dest: /home/{{ target_user }}/.ssh/config
    mode: '0644'
