---
- name: Gerar chave SSH se não existir
  command: ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa

- name: Copiar chave pública
  copy:
    content: "{{ ssh_pub_key }}"
    dest: /root/.ssh/authorized_keys

- name: Copiar chave privada
  copy:
    content: "{{ ssh_key }}"
    dest: /root/.ssh/id_rsa
    mode: '0600'

- name: Copiar arquivo de configuração SSH
  copy:
    content: "{{ ssh_config }}"
    dest: /root/.ssh/config
    mode: '0644'
