---
- name: Atualizar apt e instalar pacotes básicos
  become: yes
  apt:
    name:
      - curl
      - wget
      - git
      - joe
      - htop
      - ncdu
      - net-tools
      - dnsutils
      - nmap
      - tree
      - unzip
      - build-essential
      - iptables-persistent
    state: present
    update_cache: yes

